apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: your-storage-class-name
  resources:
    requests:
      storage: 200Gi
